require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const morgan = require('morgan');
const path = require('path');
const connectDB = require('./config/db');
const authRoutes = require('./routes/authRoutes');
const routeRoutes = require('./routes/routeRoutes');
const app = express();
const PORT = process.env.PORT || 3000;
if (process.env.NODE_ENV !== 'test') connectDB();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json());
app.use(morgan('combined'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 200 }));
app.use(express.static(path.join(__dirname, 'public')));
app.get('/health', (req, res) => res.status(200).json({ status: 'UP', service: 'Safe Route AI', database: process.env.NODE_ENV === 'test' ? 'mock/test' : 'MongoDB', timestamp: new Date().toISOString() }));
app.use('/api/auth', authRoutes);
app.use('/api/routes', routeRoutes);
app.use((req, res) => res.status(404).json({ message: 'Endpoint not found.' }));
if (process.env.NODE_ENV !== 'test') app.listen(PORT, () => console.log(`Safe Route AI running on port ${PORT}`));
module.exports = app;
